version: "3.8"
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
